### ISSUE TITLE
Electron will not start if package.json file is completely empty

### ISSUE THREAD

**Issue by aesalazar** [EikosPartners/windowmanagerjs#13]
If I use the following script in the MAIN package.json:

`"electron": "electron ./electron/windowmanager --endpoint=http://localhost:5000/"`

But the ELECTRON package.json (in ./electron) is a completely empty file it will fail to start saying the the JSON could not be parse.  But if I simply put:

`{ }`

in the electron package.json it will work fine.  If I copy/paste the standard main.js file from electron.io tutorial and do this:

`"electron": "electron ./electron/main"`

Either version of the electron package.json file work fine.  It should be the same with windowmanager.  Would would also be great would be if there was a way to avoid needing the electron package.json altogether (but not critical).

**Comment by Dillonu** [comment]
Fixed in d4e62dc
