### ISSUE TITLE
Figure out a way to not have to copy windowmanager.js file for electron

### ISSUE THREAD

**Issue by aesalazar** [EikosPartners/windowmanagerjs#14]
As of the current version, if I want to run this script in the main package.json:

`"electron": "electron ./electron/windowmanager --endpoint=http://localhost:5000/"`

where the folder `electron` contains the electron package.json and any other build resources we have to physically copy windowmanager.js from node_modules/windowmanager/dist to that electron folder. 

We need a way to be able to point to (or link to) windowmanager.js without having to remember to copy it after, say, and upgrade.

**Comment by Dillonu** [comment]
In commit 6dd65e4 and 9f3b8cc you can now load windowmanager and start it from within a node script:
```javascript
const windowmanager = require('windowmanager');
windowmanager.start();
```

The `package.json` must then have windowmanager added a dependency, and can have the following options in `windowmanager`:
```json
{
    "main": "app.js",
    "windowmanager": {
        "endpoint": "http://domain.com/path.html",
        "config": "http://domain.com/path/to/openfin/app.json"
    },
    "dependencies": {
        "windowmanager": "^0.13.1"
    }
}
```
