### ISSUE TITLE
Window Drag-lock in Edge Browser

### ISSUE THREAD

**Issue by aesalazar** [EikosPartners/windowmanagerjs#3]
A problem with window drag lock in MS Edge when _dragStart is called.  This kind of describes the problem:

http://stackoverflow.com/questions/11533098/how-to-catch-mouse-up-event-outside-of-element

Basically, with Edge, mouseup and mousemove will not fire if the mouse is beyond the edge of a window.  When you click the title bar and drag the call to .restore() will move the window well below the mouse pointer while dragging is still set to true.  So moving the mouse to the window will cause it to jump when it reenters perpetually.  

Window factory would either have to watch for mouseleave which will probably ruin the UX since they user would have to move the mouse very carefully so as not to go beyond the window edge when dragging or wire the handlers to the parent container.

**Comment by Dillonu** [comment]
This problem now seems to have evolved into a new glitch. It now appears to work in Edge, however Edge's event object for mousemove doesn't take into account scaling for screenX and screenY. Now when a window is dragged, it will move 2x as fast on a monitor with 200% scaling, or half as fast for 50%, ect. Might have to add code to check if it is running in Edge, and use devicePixelRatio to determine the new window position.

**Comment by Dillonu** [comment]
I feel the best way to solve this is to wire the handlers to the launcher window (parent container). Adding this on the list of todos to fix.

**Comment by Dillonu** [comment]
Fixed in 1e859a0. Moved the listeners to the launcher window.
